# Additional plugin properties are set in */plugin.properties for each target IJP
pluginGroup=dev.sebastiano.jewel.ijplugin
pluginName=jewel-ijp-template
pluginRepositoryUrl=https://github.com/rock3r/jewel-ijp-template
pluginVersion=0.0.1
platformType=IC

# This version must be aligned to the highest plugin-*'s module value
platformVersion=2025.1

jdk.level=21
gradleVersion=8.13

kotlin.stdlib.default.dependency=false
org.gradle.configuration-cache=true
org.gradle.caching=true
